// Mixing formulas from the PristonTale EU wiki:
// https://wiki.pristontale.eu/en/Basic_Information/mixing
// Generated from the wiki tables — effects and required sheltoms, verbatim.

export interface SheltomReq { name: string; qty: number }
export interface MixFormula { effects: string[]; sheltoms: SheltomReq[] }
export interface MixCategory { id: string; name: string; icon: string; formulas: MixFormula[] }

export const sheltomIcon = (name: string): string => `/sheltoms/${name.toLowerCase()}.png`;

export const MIX_CATEGORIES: MixCategory[] = [
  {
    id: "weapons", name: "Weapons", icon: "⚔️",
    formulas: [
      { effects: ["Attack Rating +10%", "Min DMG +1", "Max DMG +4"], sheltoms: [{ name: "Lucidy", qty: 1 }, { name: "Sereneo", qty: 1 }, { name: "Fadeo", qty: 2 }, { name: "Sparky", qty: 4 }, { name: "Raident", qty: 1 }] },
      { effects: ["Attack Rating +40", "Min DMG +3", "Max DMG +5"], sheltoms: [{ name: "Sereneo", qty: 1 }, { name: "Fadeo", qty: 3 }, { name: "Sparky", qty: 5 }, { name: "Murky", qty: 1 }] },
      { effects: ["Critical +4%", "Attack Rating +60%", "Max DMG +6"], sheltoms: [{ name: "Raident", qty: 5 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 2 }] },
      { effects: ["Attack Rating +80", "Critical +2%", "Min & Max DMG +4"], sheltoms: [{ name: "Fadeo", qty: 2 }, { name: "Sparky", qty: 2 }, { name: "Raident", qty: 2 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }] },
      { effects: ["Critical +4%", "Add MP +20", "Min & Max DMG +6"], sheltoms: [{ name: "Fadeo", qty: 3 }, { name: "Sparky", qty: 3 }, { name: "Transparo", qty: 2 }, { name: "Devine", qty: 2 }] },
      { effects: ["Attack Rating +60", "Add HP +40", "Min & Max DMG +6"], sheltoms: [{ name: "Fadeo", qty: 2 }, { name: "Sparky", qty: 2 }, { name: "Murky", qty: 1 }, { name: "Devine", qty: 3 }] },
      { effects: ["Critical +4%"], sheltoms: [{ name: "Celesto", qty: 1 }] },
      { effects: ["Attack Rating +100", "Critical +3%", "Min & Max DMG +6"], sheltoms: [{ name: "Sparky", qty: 2 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 3 }] },
    ],
  },
  {
    id: "armors", name: "Armors & Robes", icon: "🛡️",
    formulas: [
      { effects: ["Absorb +25"], sheltoms: [{ name: "Sereneo", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }] },
      { effects: ["Add HP +40"], sheltoms: [{ name: "Sereneo", qty: 1 }, { name: "Sparky", qty: 4 }, { name: "Murky", qty: 1 }] },
      { effects: ["Add HP +60"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }] },
      { effects: ["Defense Rating +40", "Absorb +3.0"], sheltoms: [{ name: "Fadeo", qty: 4 }, { name: "Raident", qty: 4 }, { name: "Murky", qty: 3 }] },
      { effects: ["Defense Rating +20", "Absorb +3.4"], sheltoms: [{ name: "Sparky", qty: 2 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }] },
      { effects: ["Add HP +80"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Devine", qty: 4 }] },
      { effects: ["Defense Rating +40", "Add MP +30"], sheltoms: [{ name: "Sparky", qty: 1 }, { name: "Raident", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Devine", qty: 3 }] },
      { effects: ["Absorb +3.5", "Add HP +40"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 2 }] },
      { effects: ["Defense Rating +50"], sheltoms: [{ name: "Celesto", qty: 1 }] },
      { effects: ["Add HP +50"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }] },
      { effects: ["Defense Rating +50", "Add MP +40"], sheltoms: [{ name: "Sparky", qty: 2 }, { name: "Transparo", qty: 2 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Absorb +4.0", "Add HP +50"], sheltoms: [{ name: "Raident", qty: 3 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 1 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Defense Rating +50", "Absorb +4.0"], sheltoms: [{ name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 5 }] },
      { effects: ["Defense Rating +60", "Add MP +50"], sheltoms: [{ name: "Devine", qty: 5 }, { name: "Celesto", qty: 5 }] },
      { effects: ["Absorb +4.0", "Add HP +80"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 5 }, { name: "Devine", qty: 1 }, { name: "Celesto", qty: 5 }] },
    ],
  },
  {
    id: "shields", name: "Shields", icon: "🔰",
    formulas: [
      { effects: ["Block Rating +1%"], sheltoms: [{ name: "Murky", qty: 1 }] },
      { effects: ["Add HP +20"], sheltoms: [{ name: "Devine", qty: 1 }] },
      { effects: ["Absorb +3", "Block Rating +4%"], sheltoms: [{ name: "Fadeo", qty: 1 }, { name: "Raident", qty: 4 }, { name: "Murky", qty: 1 }] },
      { effects: ["Block Rating +5%"], sheltoms: [{ name: "Fadeo", qty: 5 }, { name: "Transparo", qty: 5 }, { name: "Murky", qty: 1 }] },
      { effects: ["Defense Rating +40", "Block Rating +2%"], sheltoms: [{ name: "Sereneo", qty: 4 }, { name: "Fadeo", qty: 4 }, { name: "Murky", qty: 1 }] },
      { effects: ["Defense Rating +20", "Block Rating +4%"], sheltoms: [{ name: "Sereneo", qty: 2 }, { name: "Fadeo", qty: 1 }, { name: "Sparky", qty: 1 }, { name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }] },
      { effects: ["Defense Rating +40", "Add MP +10", "Add Stamina +50"], sheltoms: [{ name: "Lucidy", qty: 4 }, { name: "Sereneo", qty: 1 }, { name: "Transparo", qty: 1 }, { name: "Devine", qty: 1 }] },
      { effects: ["Block Rating +3%", "Add HP +40"], sheltoms: [{ name: "Transparo", qty: 3 }, { name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }] },
      { effects: ["Absorb +5", "Add MP +20"], sheltoms: [{ name: "Raident", qty: 5 }, { name: "Devine", qty: 2 }] },
      { effects: ["Absorb +3", "Add HP +80"], sheltoms: [{ name: "Raident", qty: 3 }, { name: "Transparo", qty: 1 }, { name: "Devine", qty: 2 }] },
      { effects: ["Add HP +80"], sheltoms: [{ name: "Celesto", qty: 1 }] },
      { effects: ["Defense Rating +50", "Add MP +20", "Add Stamina +60"], sheltoms: [{ name: "Sparky", qty: 1 }, { name: "Raident", qty: 3 }, { name: "Murky", qty: 2 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Block Rating +4%", "Add HP +60"], sheltoms: [{ name: "Raident", qty: 2 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 3 }, { name: "Celesto", qty: 2 }] },
      { effects: ["Absorb +10", "Add MP +30"], sheltoms: [{ name: "Transparo", qty: 3 }, { name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }] },
      { effects: ["Defense Rating +60", "Block Rating +5%"], sheltoms: [{ name: "Murky", qty: 3 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Absorb +10", "Add HP +40", "Add MP +20"], sheltoms: [{ name: "Devine", qty: 5 }, { name: "Celesto", qty: 5 }] },
      { effects: ["Block Rating +4%", "Add HP +100"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 5 }] },
    ],
  },
  {
    id: "orbs", name: "Orbs", icon: "🔮",
    formulas: [
      { effects: ["Defense Rating +10%"], sheltoms: [{ name: "Sereneo", qty: 2 }, { name: "Fadeo", qty: 2 }, { name: "Sparky", qty: 1 }] },
      { effects: ["Defense Rating +40"], sheltoms: [{ name: "Fadeo", qty: 1 }, { name: "Raident", qty: 4 }, { name: "Murky", qty: 1 }] },
      { effects: ["Defense Rating +10", "MP Regen +0.6"], sheltoms: [{ name: "Fadeo", qty: 3 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 1 }] },
      { effects: ["Defense Rating +50", "Absorb +1.0"], sheltoms: [{ name: "Sereneo", qty: 5 }, { name: "Fadeo", qty: 5 }, { name: "Murky", qty: 1 }] },
      { effects: ["Defense Rating +40", "MP Regen 0.4"], sheltoms: [{ name: "Sereneo", qty: 2 }, { name: "Fadeo", qty: 1 }, { name: "Sparky", qty: 1 }, { name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }] },
      { effects: ["MP Regen 0.5", "Add MP +40"], sheltoms: [{ name: "Lucidy", qty: 5 }, { name: "Sereneo", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Devine", qty: 2 }] },
      { effects: ["Defense Rating +10", "MP Regen +0.4", "Add Stamina +40"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }] },
      { effects: ["Add MP +50", "Add Stamina +50"], sheltoms: [{ name: "Sparky", qty: 2 }, { name: "Raident", qty: 5 }, { name: "Devine", qty: 2 }] },
      { effects: ["Absorb Rating + 1.0", "MP Regen +0.6", "Add HP +20"], sheltoms: [{ name: "Raident", qty: 5 }, { name: "Transparo", qty: 2 }, { name: "Devine", qty: 2 }] },
      { effects: ["Add MP +30"], sheltoms: [{ name: "Celesto", qty: 1 }] },
      { effects: ["Defense Rating +20", "MP Regen +0.8", "Add Stamina +50"], sheltoms: [{ name: "Sparky", qty: 2 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }] },
      { effects: ["Add MP +60", "Add Stamina +50"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Absorb +1.5", "MP Regen +1.0", "Add HP +30"], sheltoms: [{ name: "Raident", qty: 2 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 3 }] },
      { effects: ["Defense Rating +30", "MP Regen +1.0", "Add Stamina +50"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 4 }] },
      { effects: ["Absorb +2.0", "MP Regen +1.2", "Add HP +30"], sheltoms: [{ name: "Devine", qty: 5 }, { name: "Celesto", qty: 5 }] },
      { effects: ["Defense Rating +20", "MP Regen +1.2", "Add MP +60"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 5 }, { name: "Devine", qty: 1 }, { name: "Celesto", qty: 5 }] },
    ],
  },
  {
    id: "gauntlets", name: "Gauntlets", icon: "🧤",
    formulas: [
      { effects: ["Defense +225"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 5 }] },
      { effects: ["Absorb +3"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 6 }] },
      { effects: ["Defense +270"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 6 }] },
      { effects: ["Absorb +4"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 7 }] },
      { effects: ["Defense +315"], sheltoms: [{ name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 6 }] },
      { effects: ["Absorb +5"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 7 }] },
      { effects: ["Defense +360"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 6 }] },
      { effects: ["Absorb +6"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 8 }] },
      { effects: ["Defense +405"], sheltoms: [{ name: "Celesto", qty: 1 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 7 }] },
      { effects: ["Absorb +7"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 8 }] },
      { effects: ["Defense +450"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 8 }] },
      { effects: ["Absorb +8"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 10 }] },
      { effects: ["Defense +495"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 2 }, { name: "Bellum", qty: 8 }] },
      { effects: ["Absorb +9"], sheltoms: [{ name: "Enigma", qty: 2 }, { name: "Bellum", qty: 10 }] },
      { effects: ["Defense +540"], sheltoms: [{ name: "Bellum", qty: 2 }, { name: "Oredo", qty: 10 }] },
      { effects: ["Absorb +10"], sheltoms: [{ name: "Oredo", qty: 12 }] },
      { effects: ["Resistance +16"], sheltoms: [{ name: "Mirage", qty: 1 }, { name: "Inferna", qty: 1 }, { name: "Enigma", qty: 1 }, { name: "Bellum", qty: 3 }, { name: "Oredo", qty: 6 }] },
    ],
  },
  {
    id: "boots", name: "Boots", icon: "👢",
    formulas: [
      { effects: ["Run Speed +0.6", "Stamina +160", "MP +60"], sheltoms: [{ name: "Raident", qty: 2 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 3 }] },
      { effects: ["Run Speed +0.6", "MP +120"], sheltoms: [{ name: "Sparky", qty: 1 }, { name: "Raident", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 3 }] },
      { effects: ["Run Speed +1.2", "Stamina +80", "MP +40"], sheltoms: [{ name: "Raident", qty: 2 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 3 }] },
      { effects: ["Run Speed +2.4"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 6 }] },
      { effects: ["Run Speed +0.7", "Stamina +200", "MP +75"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 4 }] },
      { effects: ["Run Speed +0.7", "MP +150"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 4 }] },
      { effects: ["Run Speed +1.4", "Stamina +100", "MP +50"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 4 }] },
      { effects: ["Run Speed +2.8"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 7 }] },
      { effects: ["Run Speed +0.8", "Stamina +240", "MP +90"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 4 }] },
      { effects: ["Run Speed +0.8", "MP +180"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 4 }] },
      { effects: ["Run Speed +1.6", "Stamina +120", "MP +60"], sheltoms: [{ name: "Murky", qty: 1 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 5 }] },
      { effects: ["Run Speed +3.2"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 7 }] },
      { effects: ["Run Speed +0.9", "Stamina +280", "MP +105"], sheltoms: [{ name: "Devine", qty: 3 }, { name: "Celesto", qty: 3 }, { name: "Mirage", qty: 4 }] },
      { effects: ["Run Speed +0.9", "MP +210"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 4 }] },
      { effects: ["Run Speed +1.8", "Stamina +140", "MP +70"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 6 }] },
      { effects: ["Run Speed +3.6"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 8 }] },
      { effects: ["Run Speed +1", "Stamina +320", "MP +120"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 3 }, { name: "Inferna", qty: 5 }] },
      { effects: ["Run Speed +1", "MP +240"], sheltoms: [{ name: "Devine", qty: 1 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 5 }] },
      { effects: ["Run Speed +2", "Stamina +160", "MP +80"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 6 }] },
      { effects: ["Run Speed +4"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 8 }] },
      { effects: ["Run Speed +1.1", "Stamina +360", "MP +135"], sheltoms: [{ name: "Mirage", qty: 3 }, { name: "Inferna", qty: 3 }, { name: "Enigma", qty: 6 }] },
      { effects: ["Run Speed +1.1", "MP +270"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 6 }] },
      { effects: ["Run Speed +2.2", "Stamina +180", "MP +90"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 4 }, { name: "Enigma", qty: 6 }] },
      { effects: ["Run Speed +4.4"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 10 }] },
      { effects: ["Run Speed +1.2", "Stamina +400", "MP +150"], sheltoms: [{ name: "Inferna", qty: 3 }, { name: "Enigma", qty: 3 }, { name: "Bellum", qty: 6 }] },
      { effects: ["Run Speed +1.2", "MP +300"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 2 }, { name: "Bellum", qty: 6 }] },
      { effects: ["Run Speed +2.4", "Stamina +200", "MP +100"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 4 }, { name: "Bellum", qty: 6 }] },
      { effects: ["Run Speed +4.8"], sheltoms: [{ name: "Enigma", qty: 2 }, { name: "Bellum", qty: 10 }] },
      { effects: ["Run Speed +1.3", "Stamina +450", "MP +170"], sheltoms: [{ name: "Enigma", qty: 2 }, { name: "Bellum", qty: 2 }, { name: "Oredo", qty: 8 }] },
      { effects: ["Run Speed +1.3", "MP +340"], sheltoms: [{ name: "Inferna", qty: 1 }, { name: "Enigma", qty: 1 }, { name: "Bellum", qty: 2 }, { name: "Oredo", qty: 8 }] },
      { effects: ["Run Speed +2.6", "Stamina +225", "MP +120"], sheltoms: [{ name: "Bellum", qty: 4 }, { name: "Oredo", qty: 8 }] },
      { effects: ["Run Speed +5.2"], sheltoms: [{ name: "Oredo", qty: 12 }] },
    ],
  },
  {
    id: "bracelets", name: "Bracelets", icon: "📿",
    formulas: [
      { effects: ["Attack Rating +160", "Potion Count +20", "HP +25"], sheltoms: [{ name: "Sparky", qty: 1 }, { name: "Raident", qty: 1 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 3 }] },
      { effects: ["Attack Rating +80", "Potion Count +10", "HP +50"], sheltoms: [{ name: "Raident", qty: 2 }, { name: "Transparo", qty: 3 }, { name: "Murky", qty: 3 }] },
      { effects: ["Attack Rating +240"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Transparo", qty: 2 }, { name: "Murky", qty: 5 }] },
      { effects: ["HP +100"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 6 }] },
      { effects: ["Attack Rating +190", "Potion Count +22", "HP +30"], sheltoms: [{ name: "Raident", qty: 1 }, { name: "Transparo", qty: 1 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 4 }] },
      { effects: ["Attack Rating +95", "Potion Count +11", "HP +60"], sheltoms: [{ name: "Transparo", qty: 2 }, { name: "Murky", qty: 3 }, { name: "Devine", qty: 4 }] },
      { effects: ["Attack Rating +285"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 2 }, { name: "Devine", qty: 6 }] },
      { effects: ["HP +120"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 7 }] },
      { effects: ["Attack Rating +220", "Potion Count +24", "HP +35"], sheltoms: [{ name: "Transparo", qty: 1 }, { name: "Murky", qty: 1 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 4 }] },
      { effects: ["Attack Rating +110", "Potion Count +12", "HP +70"], sheltoms: [{ name: "Murky", qty: 2 }, { name: "Devine", qty: 3 }, { name: "Celesto", qty: 4 }] },
      { effects: ["Attack Rating +330"], sheltoms: [{ name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 6 }] },
      { effects: ["HP +140"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 7 }] },
      { effects: ["Attack Rating +240", "Potion Count +26", "HP +40"], sheltoms: [{ name: "Murky", qty: 1 }, { name: "Devine", qty: 2 }, { name: "Celesto", qty: 3 }, { name: "Mirage", qty: 4 }] },
      { effects: ["Attack Rating +120", "Potion Count +13", "HP +80"], sheltoms: [{ name: "Devine", qty: 3 }, { name: "Celesto", qty: 3 }, { name: "Mirage", qty: 4 }] },
      { effects: ["Attack Rating +360"], sheltoms: [{ name: "Devine", qty: 2 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 6 }] },
      { effects: ["HP +160"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 8 }] },
      { effects: ["Attack Rating +260", "Potion Count +28", "HP +45"], sheltoms: [{ name: "Devine", qty: 1 }, { name: "Celesto", qty: 2 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 5 }] },
      { effects: ["Attack Rating +130", "Potion Count +14", "HP +90"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 3 }, { name: "Inferna", qty: 5 }] },
      { effects: ["Attack Rating +390"], sheltoms: [{ name: "Celesto", qty: 1 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 7 }] },
      { effects: ["HP +180"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 8 }] },
      { effects: ["Attack Rating +280", "Potion Count +30", "HP +25"], sheltoms: [{ name: "Celesto", qty: 2 }, { name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 6 }] },
      { effects: ["Attack Rating +140", "Potion Count +15", "HP +50"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 4 }, { name: "Enigma", qty: 6 }] },
      { effects: ["Attack Rating +420"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 8 }] },
      { effects: ["HP +200"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 10 }] },
      { effects: ["Attack Rating +280", "Potion Count +32", "HP +30"], sheltoms: [{ name: "Mirage", qty: 2 }, { name: "Inferna", qty: 2 }, { name: "Enigma", qty: 2 }, { name: "Bellum", qty: 6 }] },
      { effects: ["Attack Rating +150", "Potion Count +15", "HP +60"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 4 }, { name: "Bellum", qty: 6 }] },
      { effects: ["Attack Rating +450"], sheltoms: [{ name: "Inferna", qty: 2 }, { name: "Enigma", qty: 2 }, { name: "Bellum", qty: 8 }] },
      { effects: ["HP +220"], sheltoms: [{ name: "Enigma", qty: 2 }, { name: "Bellum", qty: 10 }] },
      { effects: ["Attack Rating +300", "Potion Count +34", "HP +60"], sheltoms: [{ name: "Inferna", qty: 1 }, { name: "Enigma", qty: 1 }, { name: "Bellum", qty: 2 }, { name: "Oredo", qty: 8 }] },
      { effects: ["Attack Rating +160", "Potion Count +16", "HP +120"], sheltoms: [{ name: "Enigma", qty: 1 }, { name: "Bellum", qty: 3 }, { name: "Oredo", qty: 8 }] },
      { effects: ["Attack Rating +480"], sheltoms: [{ name: "Bellum", qty: 2 }, { name: "Oredo", qty: 10 }] },
      { effects: ["HP +240"], sheltoms: [{ name: "Oredo", qty: 12 }] },
    ],
  },
];

export const ALL_SHELTOMS: string[] = ["Bellum", "Celesto", "Devine", "Enigma", "Fadeo", "Inferna", "Lucidy", "Mirage", "Murky", "Oredo", "Raident", "Sereneo", "Sparky", "Transparo"];
